### ISSUE TITLE
решить вопрос по поводу пользовательского интерфейса

### ISSUE THREAD

**Issue by FusionFrost** [mirea-fcyb-2015/text-struct#4]
решить вопрос по поводу пользовательского интерфейса

**Comment by BerezinAlexander** [comment]
Сейчас нет смысла мне брать твой ПИ, т. к. у меня есть тестовая панель с кучей кнопок, которых в релизе не будет. Поэтому как закончу свои алгоритмы, так снесу все тестовые кнопки и возьму твой интерфейс.
